/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_crc;

import domain.AlgoritmoCRC;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class EmisorCRC extends javax.swing.JFrame {

    /**
     * Intancias y variables de clase
     */
    int xCursor, yCursor;
    PanelEmisor pe = new PanelEmisor();

    public EmisorCRC() {

        initComponents();
        /**
         * Se conmienza bloquean las cajas de texto de CRC y TX asi como tambien
         * el boton enviar
         */
        
        mostrarPanel(pe);
        pe.crcText.setEnabled(false);
        pe.txText.setEnabled(false);
        pe.panelBotonEnviar.setEnabled(false);
        pe.enviarLabel.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelBotonEmisor = new javax.swing.JPanel();
        emisorLabel = new javax.swing.JLabel();
        panelBotonReceptor = new javax.swing.JPanel();
        receptorLabel = new javax.swing.JLabel();
        panelBotonSalir = new javax.swing.JPanel();
        salirLabel1 = new javax.swing.JLabel();
        panelTitulo = new javax.swing.JPanel();
        proyectoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        contenedor = new javax.swing.JPanel();
        cabezera = new javax.swing.JPanel();
        panelSalir = new javax.swing.JPanel();
        salirLabel = new javax.swing.JLabel();
        rolLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        backGround.setBackground(new java.awt.Color(255, 255, 255));
        backGround.setForeground(new java.awt.Color(204, 204, 204));
        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBotones.setBackground(new java.awt.Color(127, 80, 220));

        jPanel2.setBackground(new java.awt.Color(182, 154, 234));

        panelBotonEmisor.setBackground(new java.awt.Color(182, 154, 234));
        panelBotonEmisor.setPreferredSize(new java.awt.Dimension(140, 56));

        emisorLabel.setBackground(new java.awt.Color(255, 255, 255));
        emisorLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        emisorLabel.setForeground(new java.awt.Color(255, 255, 255));
        emisorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emisorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carta.png"))); // NOI18N
        emisorLabel.setText("Emisor");
        emisorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emisorLabel.setMaximumSize(new java.awt.Dimension(71, 17));
        emisorLabel.setMinimumSize(new java.awt.Dimension(71, 17));
        emisorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emisorLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emisorLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emisorLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBotonEmisorLayout = new javax.swing.GroupLayout(panelBotonEmisor);
        panelBotonEmisor.setLayout(panelBotonEmisorLayout);
        panelBotonEmisorLayout.setHorizontalGroup(
            panelBotonEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emisorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelBotonEmisorLayout.setVerticalGroup(
            panelBotonEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emisorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        panelBotonReceptor.setBackground(new java.awt.Color(182, 154, 234));

        receptorLabel.setBackground(new java.awt.Color(255, 255, 255));
        receptorLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        receptorLabel.setForeground(new java.awt.Color(255, 255, 255));
        receptorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receptorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mensaje.png"))); // NOI18N
        receptorLabel.setText("Receptor");
        receptorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        receptorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receptorLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                receptorLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                receptorLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBotonReceptorLayout = new javax.swing.GroupLayout(panelBotonReceptor);
        panelBotonReceptor.setLayout(panelBotonReceptorLayout);
        panelBotonReceptorLayout.setHorizontalGroup(
            panelBotonReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receptorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelBotonReceptorLayout.setVerticalGroup(
            panelBotonReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receptorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        panelBotonSalir.setBackground(new java.awt.Color(182, 154, 234));
        panelBotonSalir.setPreferredSize(new java.awt.Dimension(140, 56));

        salirLabel1.setBackground(new java.awt.Color(255, 255, 255));
        salirLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        salirLabel1.setForeground(new java.awt.Color(255, 255, 255));
        salirLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image.png"))); // NOI18N
        salirLabel1.setText("Salir");
        salirLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirLabel1.setMaximumSize(new java.awt.Dimension(71, 17));
        salirLabel1.setMinimumSize(new java.awt.Dimension(71, 17));
        salirLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBotonSalirLayout = new javax.swing.GroupLayout(panelBotonSalir);
        panelBotonSalir.setLayout(panelBotonSalirLayout);
        panelBotonSalirLayout.setHorizontalGroup(
            panelBotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBotonSalirLayout.setVerticalGroup(
            panelBotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotonEmisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotonReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panelBotonEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        backGround.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 430));

        panelTitulo.setBackground(new java.awt.Color(13, 134, 134));

        proyectoLabel.setBackground(new java.awt.Color(0, 0, 0));
        proyectoLabel.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        proyectoLabel.setForeground(new java.awt.Color(255, 255, 255));
        proyectoLabel.setText("CALCULADORA CRC");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                        .addComponent(proyectoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(proyectoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        backGround.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 80));

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        backGround.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 510, 430));

        cabezera.setBackground(new java.awt.Color(12, 99, 93));
        cabezera.setForeground(new java.awt.Color(255, 255, 255));
        cabezera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cabezeraMouseDragged(evt);
            }
        });
        cabezera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cabezeraMousePressed(evt);
            }
        });

        panelSalir.setBackground(new java.awt.Color(12, 99, 93));
        panelSalir.setForeground(new java.awt.Color(255, 255, 255));

        salirLabel.setBackground(new java.awt.Color(238, 99, 93));
        salirLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        salirLabel.setForeground(new java.awt.Color(0, 0, 0));
        salirLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirLabel.setText("X");
        salirLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirLabel.setPreferredSize(new java.awt.Dimension(40, 40));
        salirLabel.setRequestFocusEnabled(false);
        salirLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        rolLabel.setBackground(new java.awt.Color(255, 255, 255));
        rolLabel.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        rolLabel.setForeground(new java.awt.Color(255, 255, 255));
        rolLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rolLabel.setText("EMISOR");

        javax.swing.GroupLayout cabezeraLayout = new javax.swing.GroupLayout(cabezera);
        cabezera.setLayout(cabezeraLayout);
        cabezeraLayout.setHorizontalGroup(
            cabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabezeraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cabezeraLayout.setVerticalGroup(
            cabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraLayout.createSequentialGroup()
                .addGroup(cabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rolLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        backGround.add(cabezera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cabezeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabezeraMousePressed
        xCursor = evt.getX();
        yCursor = evt.getY();
    }//GEN-LAST:event_cabezeraMousePressed

    private void cabezeraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabezeraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xCursor, y - yCursor);
    }//GEN-LAST:event_cabezeraMouseDragged

    private void salirLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirLabelMouseClicked

    private void salirLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabelMouseEntered
        panelSalir.setBackground(Color.red);
        salirLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_salirLabelMouseEntered

    private void salirLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabelMouseExited
        panelSalir.setBackground(new Color(12, 99, 93));
        salirLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_salirLabelMouseExited

    private void emisorLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emisorLabelMouseEntered
        panelBotonEmisor.setBackground(new Color(211, 195, 242));
    }//GEN-LAST:event_emisorLabelMouseEntered

    private void emisorLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emisorLabelMouseExited
        panelBotonEmisor.setBackground(new Color(182, 154, 234));
    }//GEN-LAST:event_emisorLabelMouseExited

    private void receptorLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receptorLabelMouseEntered
        panelBotonReceptor.setBackground(new Color(211, 195, 242));
    }//GEN-LAST:event_receptorLabelMouseEntered

    private void receptorLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receptorLabelMouseExited
        panelBotonReceptor.setBackground(new Color(182, 154, 234));
    }//GEN-LAST:event_receptorLabelMouseExited

    private void receptorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receptorLabelMouseClicked
        pe.mostrarPanelReceptor();
        rolLabel.setText("RECEPTOR");
    }//GEN-LAST:event_receptorLabelMouseClicked

    private void emisorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emisorLabelMouseClicked
       
        PanelEmisor emisor = new PanelEmisor(pe.mensaje, pe.pGnerador, pe.valorCRC, pe.tx);
        mostrarPanel(emisor);
        rolLabel.setText("EMISOR");
        
    }//GEN-LAST:event_emisorLabelMouseClicked

    private void salirLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabel1MouseEntered
         panelBotonSalir.setBackground(new Color(211, 195, 242));
    }//GEN-LAST:event_salirLabel1MouseEntered

    private void salirLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabel1MouseExited
       panelBotonSalir.setBackground(new Color(182, 154, 234));
    }//GEN-LAST:event_salirLabel1MouseExited

    private void salirLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirLabel1MouseClicked

    public void mostrarPanel(JPanel p) {
        p.setSize(510, 430);
        p.setLocation(0, 0);
        contenedor.removeAll();
        contenedor.add(p, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmisorCRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmisorCRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmisorCRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmisorCRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmisorCRC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGround;
    private javax.swing.JPanel cabezera;
    public static javax.swing.JPanel contenedor;
    private javax.swing.JLabel emisorLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBotonEmisor;
    private javax.swing.JPanel panelBotonReceptor;
    private javax.swing.JPanel panelBotonSalir;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel proyectoLabel;
    private javax.swing.JLabel receptorLabel;
    public static javax.swing.JLabel rolLabel;
    private javax.swing.JLabel salirLabel;
    private javax.swing.JLabel salirLabel1;
    // End of variables declaration//GEN-END:variables
}
