/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_crc;

import java.awt.Color;


/**
 *
 * @author andre
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    int xCursor, yCursor;
    EmisorCRC emisorCRC = new EmisorCRC();
    public Menu() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        cabezera = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        salirLabel = new javax.swing.JLabel();
        listaOpciones = new javax.swing.JComboBox<>();
        botonOK = new javax.swing.JPanel();
        okLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        backGround.setBackground(new java.awt.Color(255, 255, 255));
        backGround.setForeground(new java.awt.Color(255, 255, 255));
        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabezera.setBackground(new java.awt.Color(12, 99, 93));
        cabezera.setForeground(new java.awt.Color(255, 255, 255));
        cabezera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cabezeraMouseDragged(evt);
            }
        });
        cabezera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cabezeraMousePressed(evt);
            }
        });

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("SISTEMA DE CALCULO DE CRC - REDES LOCALES");

        panelSalir.setBackground(new java.awt.Color(12, 99, 93));
        panelSalir.setForeground(new java.awt.Color(255, 255, 255));

        salirLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        salirLabel.setForeground(new java.awt.Color(0, 0, 0));
        salirLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirLabel.setText("X");
        salirLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cabezeraLayout = new javax.swing.GroupLayout(cabezera);
        cabezera.setLayout(cabezeraLayout);
        cabezeraLayout.setHorizontalGroup(
            cabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(127, 127, 127)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cabezeraLayout.setVerticalGroup(
            cabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        backGround.add(cabezera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 30));

        listaOpciones.setBackground(new java.awt.Color(127, 80, 220));
        listaOpciones.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        listaOpciones.setForeground(new java.awt.Color(255, 255, 255));
        listaOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CALCULADORA CRC", "SALIR" }));
        listaOpciones.setBorder(null);
        backGround.add(listaOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 290, 40));

        botonOK.setBackground(new java.awt.Color(13, 134, 134));
        botonOK.setForeground(new java.awt.Color(255, 255, 255));
        botonOK.setPreferredSize(new java.awt.Dimension(120, 40));

        okLabel.setBackground(new java.awt.Color(255, 255, 255));
        okLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        okLabel.setForeground(new java.awt.Color(255, 255, 255));
        okLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        okLabel.setText("ENTRAR");
        okLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonOKLayout = new javax.swing.GroupLayout(botonOK);
        botonOK.setLayout(botonOKLayout);
        botonOKLayout.setHorizontalGroup(
            botonOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        botonOKLayout.setVerticalGroup(
            botonOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        backGround.add(botonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirLabelMouseClicked

    private void salirLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabelMouseEntered
        panelSalir.setBackground(Color.red);
        salirLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_salirLabelMouseEntered

    private void salirLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabelMouseExited
        panelSalir.setBackground(new Color(12, 99, 93));
        salirLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_salirLabelMouseExited

    private void cabezeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabezeraMousePressed
        xCursor = evt.getX();
        yCursor = evt.getY();
    }//GEN-LAST:event_cabezeraMousePressed

    private void cabezeraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabezeraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xCursor, y - yCursor);
    }//GEN-LAST:event_cabezeraMouseDragged

    private void okLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okLabelMouseEntered
        botonOK.setBackground(new Color(12, 99, 93));
    }//GEN-LAST:event_okLabelMouseEntered

    private void okLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okLabelMouseExited
        botonOK.setBackground(new Color(13, 134, 134));
    }//GEN-LAST:event_okLabelMouseExited

    private void okLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okLabelMouseClicked
        if (listaOpciones.getSelectedItem().toString().equals("CALCULADORA CRC")) {
            this.setVisible(false);
            emisorCRC.setVisible(true);
            
        } else if (listaOpciones.getSelectedItem().toString().equals("SALIR")) {
            System.exit(0);
        }
    }//GEN-LAST:event_okLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGround;
    private javax.swing.JPanel botonOK;
    private javax.swing.JPanel cabezera;
    private javax.swing.JComboBox<String> listaOpciones;
    private javax.swing.JLabel okLabel;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JLabel salirLabel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
