/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_crc;

import domain.AlgoritmoCRC;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author andre
 */
public class PanelReceptor extends javax.swing.JPanel {

    /**
     * Creates new form PanelReceptor
     */

    private String mensajeCorrectoIncorrecto;
    private String crc;
    private String tx;
    private String dividendo;
    private String divisor;
    
    public PanelReceptor(String mensaje, String crc, String tx, String dividendo, String divisor) {
        this();
        this.mensajeCorrectoIncorrecto = mensaje;
        this.crc = crc;
        this.tx = tx;
        this.dividendo = dividendo;
        this.divisor = divisor;
        crcReceptorText.setEnabled(false);
        txReceptorText.setEnabled(false);
        crcReceptorText.setDisabledTextColor(Color.black);
        txReceptorText.setDisabledTextColor(Color.black);
        mensajeText.setText(this.mensajeCorrectoIncorrecto);
        crcReceptorText.setText(this.crc);
        txReceptorText.setText(this.tx);
 
    }
    
    public PanelReceptor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        crcLabel = new javax.swing.JLabel();
        crcReceptorText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txLabel = new javax.swing.JLabel();
        txReceptorText = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        mensajeText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setName("panelReceptor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(530, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backGround.setBackground(new java.awt.Color(255, 255, 255));
        backGround.setForeground(new java.awt.Color(255, 255, 255));
        backGround.setPreferredSize(new java.awt.Dimension(510, 430));

        crcLabel.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        crcLabel.setForeground(new java.awt.Color(0, 0, 0));
        crcLabel.setText("CRC");

        crcReceptorText.setBackground(new java.awt.Color(255, 255, 255));
        crcReceptorText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        crcReceptorText.setForeground(new java.awt.Color(204, 204, 204));
        crcReceptorText.setText("CRC en binario");
        crcReceptorText.setBorder(null);
        crcReceptorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crcReceptorTextActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        txLabel.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txLabel.setForeground(new java.awt.Color(0, 0, 0));
        txLabel.setText("TX");

        txReceptorText.setBackground(new java.awt.Color(255, 255, 255));
        txReceptorText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txReceptorText.setForeground(new java.awt.Color(204, 204, 204));
        txReceptorText.setText("TX en binario");
        txReceptorText.setBorder(null);
        txReceptorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txReceptorTextActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        mensajeText.setBackground(new java.awt.Color(255, 255, 255));
        mensajeText.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        mensajeText.setForeground(new java.awt.Color(0, 0, 0));
        mensajeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeText.setText("Mensaje correcto!");

        javax.swing.GroupLayout backGroundLayout = new javax.swing.GroupLayout(backGround);
        backGround.setLayout(backGroundLayout);
        backGroundLayout.setHorizontalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crcLabel)
                    .addComponent(crcReceptorText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txLabel)
                    .addComponent(txReceptorText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
            .addGroup(backGroundLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(mensajeText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backGroundLayout.setVerticalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(crcLabel)
                .addGap(8, 8, 8)
                .addComponent(crcReceptorText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(txLabel)
                .addGap(8, 8, 8)
                .addComponent(txReceptorText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(mensajeText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 430));
    }// </editor-fold>//GEN-END:initComponents


    private void crcReceptorTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crcReceptorTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crcReceptorTextActionPerformed

    private void txReceptorTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txReceptorTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txReceptorTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel backGround;
    public javax.swing.JLabel crcLabel;
    public javax.swing.JTextField crcReceptorText;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel mensajeText;
    public javax.swing.JLabel txLabel;
    public javax.swing.JTextField txReceptorText;
    // End of variables declaration//GEN-END:variables
}
